config/routes.rb
Rails.application.routes.draw do
  
   #devise_for :users
   devise_for :users 
   root "welcome#home"
   
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users
 
  resources :properties

  resources :cities

  resources :countries

  resources :reviews

  resources :stays
 

end

app/models/stay.rb
class Stay < ApplicationRecord

    belongs_to :property
    belongs_to :nomad, :class_name => "User"
    has_one :review

    validates :checkin, presence: true
    validates :checkout, presence: true

    validate :dates_available

    def dates_available
        return unless errors.messages.blank?
        property_stays = Stay.all.where(property: self.property)
        property_stays.each do |stay|
            if stay.checkout <= self.checkin || self.checkout <= stay.checkin
            else
                errors.add(:stay, "for those dates is unavailable. Please choose a different property or date range.")
            end
        end
    end


    def self.top_5
        all_stays = self.all
        stay_cities = all_stays.map {|stay| stay.property.city.name}
        freq = stay_cities.inject(Hash.new(0)) { |h,v| h[v] += 1; h }
        sorted = freq.sort_by {|k,v| v}.reverse.to_h
        sorted.keys[0..4]
    end

    def stay_date_and_name
        "#{checkout} | #{property.title}"
    end

    ## method to select a country from a picklist on new stay create page
    def stay_country
    end
    ## method to select a city based on the above country (not yet working properly)
    def stay_city
        # cities = Country.all.map{|country|country.cities}
        # cities.map{|city|city.name}
    end


end

app/controllers/stays_controller.rb
class StaysController < ApplicationController

    before_action :find_stay, only: [:show, :edit, :update, :destroy]

    def index
      @stays = Stay.all
    end

    def show
    end

    def new
      if user_signed_in?
        @stay = Stay.new

      else
        redirect_to new_user_session_path
      end
    end


    def create
      @stay = Stay.new(stay_params)
     @country = @stay.property.city.country
      if @stay.save
        redirect_to  user_session_path
      else
        flash[:errors] = @stay.errors.full_messages
        redirect_to new_stay_path
      end
    end

    def edit
    end

    def update
      if @stay.update(stay_params)
        redirect_to root_path
      else
        flash[:errors] = @stay.errors.full_messages
        redirect_to edit_stay_path
      end
    end

    def destroy
      @stay.delete
      redirect_to root_path
    end

    private

    def find_stay
      @stay = Stay.find(params[:id])
    end

    def stay_params
      params.require(:stay).permit(:property_id, :nomad_id, :checkin, :checkout)
    end

end

app/views/stays/edit.html.erb
<div class="top-page">
<%= video_tag( 'kayaking.mp4', id: 'background', autoplay: true, loop: true, muted: true )%>
</div>
<div class="form">
<h1 class ="title">Edit Your Stay</h1>

<% if flash[:errors] %>
    <% flash[:errors].each do |error| %>
    <p  class="errors"><%= error %></p>
    <%end%>
<%end%>
<div>
<%= form_for(@stay) do |f| %>

    <%= f.label "Property: " %><br>
    <%= f.collection_select :property_id, Property.all.order(:city_id), :id, :formatted_name %><br>
    <%= f.hidden_field :nomad_id, :value => current_user.id %>
    <%= f.label "Check-In: " %><br>
    <%= f.date_field(:checkin, min: Date.today) %><br>
    <%= f.label "Check-Out: " %><br>
    <%= f.date_field(:checkout, min: Date.today) %><br><br/>
    <%= button_tag(type: 'submit', class: "btn btn-outline-info") do %>
        Update Stay
        <br />
        <% end %><br><br>
    <%=link_to "Cancel Stay", stay_path(@stay), method: :delete, data:{ confirm: 'Are you sure you want to cancel your Stay?' }, :class=>"btn btn-outline-info"%>

<%end%>
</div>
</div>

app/views/stays/new.html.erb
<div class="top-page">
<%= video_tag( 'kayaking.mp4', id: 'background', autoplay: true, loop: true, muted: true )%>
</div>
<div class="form">
<h1 class ="title">Schedule a New Stay</h1>

<% if flash[:errors] %>
    <% flash[:errors].each do |error| %>
    <p class="errors"><%= error %></p>
    <%end%>
<%end%>

<%= form_for(@stay) do |f| %>

    <%= f.label "Property: " %><br>
    <%= f.collection_select :property_id, Property.all.order(:city_id), :id, :formatted_name %><br>
    <%= f.hidden_field :nomad_id, :value => current_user.id %>
    <%= f.label "Check-In: " %><br>
    <%= f.date_field(:checkin, min: Date.today) %><br>
    <%= f.label "Check-Out: " %><br>
    <%= f.date_field(:checkout, min: Date.today) %><br><br/>
    <%= button_tag(type: 'submit', class: "btn btn-outline-info") do %>
        Add Stay
        <% end %>
<%end%>
</div>

app/views/stays/show.html.erb
<h1><%=@property.title%></h1>
Avg. Rating: <%=@property.average_rating%><br>

<h3> Reviews by Nomads </h3><br>
<%@property.reviews.each do |review|%>
   <p>
    <%= review.description %><br>
    <%= review.rating%><br>
    <%= review.nomad.name%>
     <% if review.nomad == current_user %>
     <button><%=link_to "Delete", edit_review_path(review)%></button>
     <%end%>
    </p>
<%end%>