config/routes.rb
Rails.application.routes.draw do
  
   #devise_for :users
   devise_for :users 
   root "welcome#home"
   
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users
 
  resources :properties

  resources :cities

  resources :countries

  resources :reviews

  resources :stays
 

end

app/models/property.rb
class Property < ApplicationRecord
    belongs_to :city
    belongs_to :host, :class_name => "User"
    has_many :stays
    has_many :reviews, :through => :stays
    has_many :nomads, :class_name => "User", :through => :stays
    has_one_attached :image


    def average_rating
       total_ratings = self.reviews.map{|review|review.rating}.sum
        total_reviews = self.reviews.count
        (total_ratings.to_f/total_reviews.to_f).round(2)
    end

    def formatted_name
        "#{title} in #{self.city.name}, #{self.city.country.name}"
    end

    def current_nomads
        if self.stays.count > 0
           early_checkin = self.stays.select{|stay|stay.checkin<= Date.today}
           late_checkout = self.stays.select{|stay|stay.checkout> Date.today}
           staying = early_checkin & late_checkout
        else
            staying = []
        end 
        staying
    end 

    def previous_nomads
        if self.stays.count > 0
            checkin = self.stays.select{|stay|stay.checkin< Date.today}
            checkout = self.stays.select{|stay|stay.checkout < Date.today}
            stayed = checkin & checkout
         else
             stayed = []
         end 
         stayed
    end 

end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController

    before_action :find_property, only: [:show, :edit, :update, :destroy]

    def index
       @properties = Property.all

    end

    def show
    end

    def new
      if user_signed_in?
        @property = Property.new
    else
        redirect_to new_user_session_path
    end

    end

    def edit
    end

    def create
      @property = Property.new(property_params)

      if @property.save
        redirect_to property_path(@property)
      else
        flash[:errors] = @property.errors.full_messages
        redirect_to new_property_path
      end

    end

    def update

      if @property.update(property_params)
        redirect_to property_path(@property)
      else
        flash[:errors] = @property.errors.full_messages
        redirect_to edit_property_path
      end

    end

    def destroy
      @property.delete
      redirect_to root_path

    end

    private

    def find_property
      @property = Property.find(params[:id])
    end

    def property_params
      params.require(:property).permit(:title, :address, :city_id, :host_id, :description, :image)
    end

end

app/views/properties/edit.html.erb
<body class="property-body">

<h1 class="title">Edit Property</h1>

<% if flash[:errors] %>
    <% flash[:errors].each do |error| %>
    <p class="errors"><%= error %></p>
    <%end%>
<%end%>

<% if @property.host == current_user %>
    <%= form_for(@property) do |f| %>
            <%= f.label "Title: " %><br>
        <%= f.text_field :title %><br>
        <%= f.label "Address: " %><br>
        <%= f.text_field :address %><br>
        <%= f.label "City: " %><br>
        <%= f.collection_select :city_id, City.all, :id, :name %><br>
        <%= f.hidden_field :host_id, :value => current_user.id %><br>
        <%= f.label "Description: " %><br>
        <%= f.text_area :description %><br>
         <%= button_tag(type: 'submit', class: "btn btn-outline-info") do %>
        Update Property
        <% end %>
        <br />
        <br />
        <%=link_to "Delete Property", property_path(@property), method: :delete, data:{ confirm: 'Are you sure you want to delete this property?' }, :class=>"btn btn-outline-info"%>
      
    <%end%>
<%end%>

app/views/properties/new.html.erb
<body class="property-body">

<h1 class="title">Create New Property Listing</h1>

<% if flash[:errors] %>
    <% flash[:errors].each do |error| %>
    <p class="errors"><%= error %></p>
    <%end%>
<%end%>

<%= form_for(@property) do |f| %>
    <%= f.label "Title: " %><br>
    <%= f.text_field :title %><br>
    <%= f.label "Address: " %><br>
    <%= f.text_field :address %><br>
    <%= f.label "City: " %><br>
    <%= f.collection_select :city_id, City.all, :id, :name %><br>
    <%= f.hidden_field :host_id, :value => current_user.id %><br>
    <%= f.label "Description: " %><br>
    <%= f.text_area :description %><br>
   <%= button_tag(type: 'submit', class: "btn btn-outline-info") do %>
        Add Property
        <% end %>
<%end%>
</body>

app/views/properties/show.html.erb
<div class="content" >

<h1 class="property-name"><%=@property.title%></h1>
<h3><%="#{@property.city.name}, #{@property.city.country.name}" %></h3>
<p>Host: <%= link_to @property.host.name, user_path(@property.host.id)%></p><br />
 <button class="rating">Avg. Rating: <%=@property.average_rating%></button>
<div>
<div id="carouselExampleControls" class="carousel slide" data-ride="carousel" >
    <div class="carousel-inner">
        <div class="carousel-item active">
        <% if @property.image.attached?%>
    
        <%=image_tag url_for(@property.image)%>
            <%else %>
        <%=image_tag url_for(["casa.jpg", "coffee_house.jpg", "modern.jpg", "poolhouse.jpg", "grass_field.jpg"].sample), style: 'height:10%;width:100%;'%>
        <%end%>
        </div>
          <div class="carousel-item">
            <%=image_tag url_for(["accra.jpg", "anghiary.jpg", "apartment.jpg", "bedroom.jpg", "italy.jpg", "loft.jpg"].sample), style: 'height:10%;width:100%;' %>
        </div>
        <div class="carousel-item">
            <%=image_tag url_for(["nusar", "riad.jpg", "roma.jpg", "rooftop.jpg", "truillia.jpg", "vintage.jpg"].sample), style: 'height:10%;width:100%;'%>
         </div>
     </div>
    <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>
</div>
<div  >
 <span style="color:#ee6055">Property description:</span><%= " #{@property.description}" %><br>
</div>

<div class="headers">
    <%if @property.host == current_user %>
         <button class="btn btn-outline-info"><%= link_to "Edit/Delete Property", edit_property_path(@property) %></button>
    <%end%>
    <%unless current_user.host? %>
        <button class="btn btn-outline-info"><%= link_to "Book A Stay", new_stay_path %></button>
    <%end%>
    <% if current_user.stays.where("property_id = ? AND checkin > ?", @property, Date.today).count > 0 %>
          <button class="btn btn-outline-info"><%= link_to "Edit/Delete Stay", edit_stay_path(Stay.find_by(nomad: current_user)) %></button>
     <%end%><br>
    
    <button class="btn btn-outline-info"><%= link_to "Add Review", new_review_path%></button>
 
</div><br /><br />


<div style="flex-grow" >
<h3 class="headers"> Reviews by Nomads: </h3>
     
<%@property.reviews.each do |review|%>
   <button class="btn btn-outline-secondary">
    <%= review.description %><br>
    <%="Rating (1-5): #{review.rating}"%><br>
    <%= "Nomad: #{review.nomad.name}"%>
    </button>
    <br />
     <% if review.nomad == current_user %>
     <button class="btn btn-outline-info"><%=link_to "Edit/Delete Review", edit_review_path(review)%></button>
     <%end%>
  
<%end%>
</div><br /><br />

<div class="headers"> 
<h4><%if @property.current_nomads.count > 0 %>
    <%= "Nomads Currently Staying Here!" %></h4>
    <%end%> 

    <%@property.current_nomads.each do |stay|%>

        <p> <%=link_to stay.nomad.name, user_path(stay.nomad.id)%></p>

    <% end %>

</div><br />


</div>