config/routes.rb
Rails.application.routes.draw do
  
   #devise_for :users
   devise_for :users 
   root "welcome#home"
   
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users
 
  resources :properties

  resources :cities

  resources :countries

  resources :reviews

  resources :stays
 

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def home
        if user_signed_in?
            if current_user.host
                render :host_home
            else
                render :nomad_home
            end
        else
            redirect_to new_user_session_path
        end
    end
    

end

app/views/welcome/host_home.html.erb
<body class="home" >
<section class="welcome3">
<h3><span>Host: </span><span style="font-family:cursive"><%="#{current_user.name.titleize}"%></span></h3>
</section>
<div class="whole-page">
<div class="card" style="width: 18rem;">
<section class="home">
<% if current_user.avatar.attached? %>
    <%= image_tag current_user.avatar, :class =>"card-img-top" %>
    <%else %>
    <%=image_tag url_for("cat.jpg"), :class =>"card-img-top"%>
<%end%>
</section>
</div>

<div class="upcoming-stays">
<h2>Your Upcoming Stays:</h2>
    <ul>
    <% if current_user.host_upcoming_stays.count > 0 %>
    <% current_user.host_upcoming_stays.each do |stay| %>
    <li><%=link_to stay, property_path(Property.find_by(title: stay)) %></li>
    <%end%>
    <%else%>
    <%= "You have no upcoming Stays. Make sure to add your property, so Nomads can book Stays! "%>
    <%end%>
    </ul>

<button class="btn btn-info"><%= link_to "Add a New Property", new_property_path, :class=>"link2" %></button>
</div>
<div class="past-stays">
<h2>View/Edit Your Properties:</h2>
    <ul>
        <% current_user.properties.each do |p| %>
        <li><%= link_to p.title, property_path(p), :class=>"link3" %><br>
            <%= "Avg. Rating: #{p.average_rating}" %></li>
        <%end%>
    </ul>
</div>

</div>

app/views/welcome/nomad_home.html.erb
<body class="home" >
<section class="welcome">
<h3><span>Nomad: </span><span style="font-family:cursive"><%="#{current_user.name.titleize}"%></span></h3>
</section>
<div class="whole-page">
<div class="card" style="width: 18rem;">
<section class="home">
<% if current_user.avatar.attached? %>
   <%= image_tag current_user.avatar, :class=>"card-img-top" %>
    <%else %>
    <%=image_tag url_for("cat.jpg"), :class =>"card-img-top"%>
<%end%>
  <div class="card-body"> 
</section>
</div> 
<div class="top-destinations">
<section>
<h3 class="card-title">My Top 5 Destinations</h5>   
      <% Stay.top_5.each do |c| %>  
      <%= link_to c, city_path(City.find_by(name: c)) %><br/>
      <%end%>
</section >
</div>
<div >
<section class="upcoming-stays">
<h3 class="card-title"> My Upcoming Stays</h3>
  
     <% if current_user.nomad_upcoming_stays.count > 0 %>
        <% current_user.nomad_upcoming_stays.each do |stay|%>
        <i class="em em-derelict_house_building" aria-role="presentation" aria-label=""></i><%=link_to stay.property.title, property_path(stay.property)%><br />
        <% end %>
     <% else %>
        <%= "You have no scheduled stays. Click below to schedule one!" %><br />
      
     <% end %>
  <br /><button class="btn btn-info"><%= link_to ".", new_stay_path %> schedule a stay </button>
</section>
</div>
<div >
<section class="past-stays" > 
<h3 class="card-title" > My Past Stays </h3>
    <ul>
     <% if current_user.nomad_completed_stays.count > 0 %>
        <% current_user.nomad_completed_stays.each do |stay|%>
        <%=link_to stay.property.title, property_path(stay.property) %>
        <% end %>
     <% else %>
        <%= "You have no past stays" %>
     <% end %>
     </ul>
     </section>
</div>
</div>

</body>