config/routes.rb
Rails.application.routes.draw do
  
   #devise_for :users
   devise_for :users 
   root "welcome#home"
   
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users
 
  resources :properties

  resources :cities

  resources :countries

  resources :reviews

  resources :stays
 

end

app/models/city.rb
class City < ApplicationRecord
    belongs_to :country
    has_many :properties

    def available_properties
        open_properties = []
        if self.city_stays.count > 0
            self.city_stays.each do |stay|
            if stay.checkout <= Date.today || (Date.today + 1.week) <= stay.checkin
                open_properties << stay.property
            end
            end
        end
         open_properties.flatten
    end

    def city_stays
        self.properties.map{|property|property.stays}.flatten
    end

end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController

    before_action :find_city, only: [:show, :edit, :update]

    def index
      @cities = City.all
    end

    def show
    end

    def new
    end

    def edit
    end

    def create
    end

    def update
    end

    private

    def find_city
      @city = City.find(params[:id])
    end

    def city_params
      params.require(:city).permit(:name, :country_id)
    end

end

app/views/cities/index.html.erb
<h1>Digital Nomad Host Cities</h1>
   <ul>
    <% @cities.each do |c| %>
   <li> <%= link_to c.name, city_path(c) %></li>
    <%end%>
    </ul>

app/views/cities/show.html.erb
<div class="city-page">
<h1 class="title"><%= @city.name %></h1>
<h2><%= link_to @city.country.name, country_path(@city.country) %></h2>
</div>
<body class="city-body"> 
<div class="available">
<h3 class="card-title"><%= "Properties available in #{@city.name} this week!" %></h3>

<% if @city.available_properties.count > 0%>
<% @city.available_properties.each do |property|%>
   <p><%= link_to property.title, property_path(property.id) %></p>
<%end%> 
 <%else %>
 <p style="color:#0077b6"><%= "No available properties this week."%></p>
 <%end%>

</div ><br />
<div class="all-properties" >
<h3><%="All Properties in #{@city.name}" %></h3>

<% @city.properties.each do |property|%>
  <p> <%= link_to property.title, property_path(property.id), :class=>"links"%></p>
<%end%>

</div>
</body>